export let data = [
  {
    _id: "66f148782168b109433f07c1",
    index: 0,
    guid: "442b1c0e-d44b-44f7-b0cf-b529463ac710",
    isActive: true,
    balance: "$2,409.38",
    picture: "http://placehold.it/32x32",
    age: 21,
    eyeColor: "green",
    name: "Aurelia Mccray",
    gender: "female",
    company: "EXOTERIC",
    email: "aureliamccray@exoteric.com",
    phone: "+1 (968) 595-3820",
    address: "293 Canda Avenue, Roland, Hawaii, 3853",
    about:
      "Nostrud dolor labore quis adipisicing aute sunt ad id consectetur mollit sit aliqua. Voluptate labore et officia veniam quis amet. Est nostrud sint do ea irure mollit. Esse excepteur nulla proident nostrud. Et minim mollit sint consequat sunt deserunt excepteur proident et tempor aliqua nisi nisi. Ullamco voluptate ea non est reprehenderit amet magna et dolore.\r\n",
    registered: "2018-04-30T09:14:43 -02:00",
    latitude: -23.117847,
    longitude: 52.596714,
    tags: ["in", "laboris", "in", "ex", "veniam", "et", "nostrud"],
    friends: [
      {
        id: 0,
        name: "Hilary Dickerson",
      },
      {
        id: 1,
        name: "Mosley Battle",
      },
      {
        id: 2,
        name: "Judith Baldwin",
      },
    ],
    greeting: "Hello, Aurelia Mccray! You have 10 unread messages.",
    favoriteFruit: "apple",
  },
  {
    _id: "66f1487834c8650b4e1d9099",
    index: 1,
    guid: "820fee07-6d0f-4ea3-9f01-a3d85de1f5e2",
    isActive: true,
    balance: "$1,201.24",
    picture: "http://placehold.it/32x32",
    age: 26,
    eyeColor: "green",
    name: "Trisha Knox",
    gender: "female",
    company: "AQUAZURE",
    email: "trishaknox@aquazure.com",
    phone: "+1 (844) 467-2836",
    address: "846 Brooklyn Avenue, Campo, Nevada, 4096",
    about:
      "Mollit nisi excepteur proident eu incididunt id ad quis. Ex do esse est nostrud dolore. Aliquip nulla magna irure nulla id aute cillum commodo exercitation et nulla anim.\r\n",
    registered: "2024-06-12T08:40:15 -02:00",
    latitude: -4.176367,
    longitude: -39.765006,
    tags: ["voluptate", "eu", "occaecat", "ullamco", "non", "in", "aliqua"],
    friends: [
      {
        id: 0,
        name: "Rodgers Duffy",
      },
      {
        id: 1,
        name: "Marcella Gutierrez",
      },
      {
        id: 2,
        name: "Potts Trevino",
      },
    ],
    greeting: "Hello, Trisha Knox! You have 8 unread messages.",
    favoriteFruit: "banana",
  },
  {
    _id: "66f14878e200eebd1635ec18",
    index: 2,
    guid: "7bc0a46d-ce79-440d-942b-1b7cd2f3fbe5",
    isActive: true,
    balance: "$3,887.62",
    picture: "http://placehold.it/32x32",
    age: 35,
    eyeColor: "blue",
    name: "Daniel Silva",
    gender: "male",
    company: "ACCEL",
    email: "danielsilva@accel.com",
    phone: "+1 (825) 537-2391",
    address: "608 Menahan Street, Coultervillle, Colorado, 7109",
    about:
      "Mollit aliquip aliquip sunt dolor sint sit. Officia quis velit dolore id ipsum ipsum. Nulla pariatur ex dolore sunt consectetur esse nulla. Ipsum eiusmod ullamco quis enim ullamco excepteur magna cillum mollit consectetur aliquip dolore Lorem.\r\n",
    registered: "2019-11-07T07:37:32 -01:00",
    latitude: 17.778803,
    longitude: -59.488568,
    tags: ["ipsum", "esse", "ex", "eu", "id", "velit", "cillum"],
    friends: [
      {
        id: 0,
        name: "Boyd Weiss",
      },
      {
        id: 1,
        name: "Bennett Armstrong",
      },
      {
        id: 2,
        name: "Brandi Allison",
      },
    ],
    greeting: "Hello, Daniel Silva! You have 3 unread messages.",
    favoriteFruit: "strawberry",
  },
  {
    _id: "66f148783cf891afbfe748b7",
    index: 3,
    guid: "9d5c2471-425a-463d-9e23-43b5bb2bd5d2",
    isActive: true,
    balance: "$3,670.46",
    picture: "http://placehold.it/32x32",
    age: 32,
    eyeColor: "blue",
    name: "Vega Delgado",
    gender: "male",
    company: "PHARMACON",
    email: "vegadelgado@pharmacon.com",
    phone: "+1 (840) 586-3900",
    address: "157 Truxton Street, Kerby, Iowa, 3612",
    about:
      "Cillum nulla cillum proident reprehenderit cupidatat proident in dolore amet. Enim anim nisi amet adipisicing. Sint ut quis aliquip nostrud duis ea qui amet commodo incididunt dolor. Consequat pariatur tempor cillum aliqua excepteur aute ad ipsum.\r\n",
    registered: "2017-05-01T03:13:19 -02:00",
    latitude: 78.599976,
    longitude: -4.754652,
    tags: [
      "consequat",
      "eiusmod",
      "excepteur",
      "ipsum",
      "laboris",
      "ut",
      "aliquip",
    ],
    friends: [
      {
        id: 0,
        name: "Gill Macias",
      },
      {
        id: 1,
        name: "Bobbie Caldwell",
      },
      {
        id: 2,
        name: "Slater Duncan",
      },
    ],
    greeting: "Hello, Vega Delgado! You have 1 unread messages.",
    favoriteFruit: "banana",
  },
  {
    _id: "66f14878a5ed1d9dc83e2870",
    index: 4,
    guid: "118b78f0-d49c-4bbe-a441-38c3dd2adf5e",
    isActive: false,
    balance: "$3,497.26",
    picture: "http://placehold.it/32x32",
    age: 30,
    eyeColor: "blue",
    name: "Elva Nunez",
    gender: "female",
    company: "KEGULAR",
    email: "elvanunez@kegular.com",
    phone: "+1 (935) 512-3669",
    address: "878 Borinquen Pl, Marshall, Massachusetts, 4102",
    about:
      "Nulla officia nisi et aliqua aute nulla veniam eu labore dolore Lorem. Proident reprehenderit esse veniam ipsum cupidatat sit tempor ad occaecat eiusmod culpa est. Sit qui laboris et in. Reprehenderit qui reprehenderit labore duis cupidatat adipisicing anim. Ut magna aute ipsum mollit mollit. Cillum amet veniam magna aliquip cillum sunt sunt. Consequat sunt cillum elit ullamco exercitation nulla.\r\n",
    registered: "2015-02-01T05:38:13 -01:00",
    latitude: 86.948806,
    longitude: 152.47356,
    tags: ["sunt", "et", "consectetur", "ullamco", "do", "aliqua", "et"],
    friends: [
      {
        id: 0,
        name: "Frederick Hart",
      },
      {
        id: 1,
        name: "Garza Mcintyre",
      },
      {
        id: 2,
        name: "Lamb Stout",
      },
    ],
    greeting: "Hello, Elva Nunez! You have 2 unread messages.",
    favoriteFruit: "apple",
  },
  {
    _id: "66f148784005b8abec11fdba",
    index: 5,
    guid: "df4a20b0-3ac3-45f4-ad5f-14bc9b5139c5",
    isActive: true,
    balance: "$2,256.91",
    picture: "http://placehold.it/32x32",
    age: 39,
    eyeColor: "brown",
    name: "Gina Santiago",
    gender: "female",
    company: "VORATAK",
    email: "ginasantiago@voratak.com",
    phone: "+1 (985) 445-3108",
    address: "559 Bush Street, Germanton, Indiana, 9421",
    about:
      "Magna culpa non dolore nisi non amet laborum occaecat incididunt laborum consectetur dolor consequat voluptate. Laborum nostrud eiusmod amet laboris exercitation dolore amet id do fugiat ullamco sit. Dolor id occaecat incididunt cillum Lorem amet. Voluptate proident irure officia commodo exercitation commodo eu velit officia. Et et aliquip est est qui tempor dolore incididunt deserunt cillum officia anim. In consectetur fugiat consectetur excepteur consectetur tempor cupidatat nulla ut ullamco culpa officia eu. Commodo deserunt et eu pariatur laborum.\r\n",
    registered: "2021-03-13T02:50:01 -01:00",
    latitude: 26.69163,
    longitude: -131.155817,
    tags: ["Lorem", "id", "voluptate", "et", "ea", "ex", "minim"],
    friends: [
      {
        id: 0,
        name: "Hallie Ratliff",
      },
      {
        id: 1,
        name: "Brooks Benjamin",
      },
      {
        id: 2,
        name: "Florence Noble",
      },
    ],
    greeting: "Hello, Gina Santiago! You have 1 unread messages.",
    favoriteFruit: "banana",
  },
  {
    _id: "66f14878bb7cb9c86401cfa6",
    index: 6,
    guid: "c22c6bec-c5f3-4070-a6e6-f6979e51323c",
    isActive: false,
    balance: "$2,040.28",
    picture: "http://placehold.it/32x32",
    age: 39,
    eyeColor: "blue",
    name: "Francis Hopkins",
    gender: "male",
    company: "ZILLATIDE",
    email: "francishopkins@zillatide.com",
    phone: "+1 (926) 476-2879",
    address: "717 Debevoise Street, Goodville, Ohio, 5198",
    about:
      "Excepteur consequat et dolor non. Adipisicing pariatur Lorem nisi duis et ea tempor laboris dolor eiusmod et irure ad. Magna sunt dolor fugiat aute consectetur Lorem eu aliqua tempor deserunt deserunt esse.\r\n",
    registered: "2018-06-25T12:32:28 -02:00",
    latitude: 70.619253,
    longitude: -77.278839,
    tags: [
      "Lorem",
      "pariatur",
      "mollit",
      "reprehenderit",
      "ipsum",
      "incididunt",
      "proident",
    ],
    friends: [
      {
        id: 0,
        name: "Marilyn Cherry",
      },
      {
        id: 1,
        name: "Tonya Sims",
      },
      {
        id: 2,
        name: "Chambers Dorsey",
      },
    ],
    greeting: "Hello, Francis Hopkins! You have 10 unread messages.",
    favoriteFruit: "apple",
  },
];
